import Man1 from '../assets/images/svg/teacher-1.svg'

export const DummyStudents = [
  {
  stu_id:'1',
	name: 'Charlee',
  email: 'user1@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生1',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'2',
	name: 'Mei',
  email: 'user2@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生2',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time:Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'3',
	name: 'Elly',
  email: 'user3@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生3',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'4',
	name: 'Azhi',
  email: 'user4@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info:'只是一個平平無奇的學生4',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'5',
	name: 'wayne',
  email: 'user5@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生5',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'6',
	name: 'ashe',
  email: 'user6@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'7',
	name: 'Mia',
  email: 'user7@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'8',
	name: 'James',
  email: 'user8@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'9',
	name: 'Sophia',
  email: 'user9@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'10',
	name: 'Olivia',
  email: 'user10@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'11',
	name: 'Alex',
  email: 'user11@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
},
  {
  stu_id:'12',
	name: 'Emma',
  email: 'user12@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: false,
  avatar: Man1,
  info: '只是一個平平無奇的學生6',
  total_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  week_lesson_time: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date()
}


];