const weekTime = Math.floor(Math.random(56) * 10 + 1) * 0.5;
const totalTime = weekTime * Math.floor(Math.random(30) * 10 + 1);

export const DummyTeachers = [
  {
  id:'1',
	name: 'user1',
  email: 'user1@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
},
  {
  id:'2',
	name: 'user2',
  email: 'user2@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
},
  {
  id:'3',
	name: 'user3',
  email: 'user3@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
},
  {
  id:'4',
	name: 'user4',
  email: 'user4@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
},
  {
  id:'5',
	name: 'user5',
  email: 'user5@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
},
  {
  id:'6',
	name: 'user6',
  email: 'user6@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: 'https://illustcenter.com/wp-content/uploads/2022/09/sdesign_00165-508x381.png',
  info: '一個懂得學習和理解學生技能的人，一個懂得學習和了解教育的人，一個懂得教育和教育的學生的判性思考和實際問題解決能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
}

];