const weekTime = Math.floor(Math.random(56) * 10 + 1) * 0.5;
const totalTime = weekTime * Math.floor(Math.random(30) * 10 + 1);
import TeacherImg1 from '../assets/images/svg/teacher-1.svg';
import TeacherImg2 from '../assets/images/svg/teacher-2.svg';
import TeacherImg3 from '../assets/images/svg/teacher-3.svg';
import TeacherImg4 from '../assets/images/svg/teacher-4.svg';
import TeacherImg5 from '../assets/images/svg/teacher-5.svg';
import TeacherImg6 from '../assets/images/svg/teacher-6.svg';

export const DummyTeachers = [
  {
  teacher_id:'1',
	name: 'Daniel',
  email: 'user1@example.com',
  password:'a1234567890',
  nation:'canada',
  is_teacher: true,
  avatar: TeacherImg1,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
  teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
  category:['雅思','日常會話','新聞英文'],
  courses:[
  {
  class_id:'1',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
  reserveDays: {
        Mon: true,
        Tue: false,
        Wed: true,
        Thu: false,
        Fri: true,
        Sat: false,
        Sun: true,
      },
  },
  ]
},
  {
  teacher_id:'2',
	name: 'Emily',
  email: 'user2@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: TeacherImg2,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
  teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
  category:['多益','托福','商用英文','日常會話','新聞英文'],
   courses:[
  {
  class_id:'1',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
    reserveDays: {
        Mon: true,
        Tue: false,
        Wed: false,
        Thu: false,
        Fri: true,
        Sat: true,
        Sun: true,
      },
},
]
},
  {
  teacher_id:'3',
	name: 'Matthew',
  email: 'user3@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: TeacherImg3,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
   teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
   category:['多益','托福','商用英文','日常會話','新聞英文'],
   courses:[
  {
  class_id:'1',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
   reserveDays: {
        Mon: true,
        Tue: true,
        Wed: false,
        Thu: false,
        Fri: true,
        Sat: true,
        Sun: true,
      },
},
]
},
  {
  teacher_id:'4',
	name: 'Isabella',
  email: 'user4@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: TeacherImg4,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
   teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
   category:['多益','日常會話','旅遊英文'],
   courses:[
  {
  class_id:'4',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
    reserveDays: {
        Mon: false,
        Tue: false,
        Wed: true,
        Thu: false,
        Fri: true,
        Sat: true,
        Sun: false,
      },
},
]
},
  {
 teacher_id:'5',
	name: 'Christopher',
  email: 'user5@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: TeacherImg5,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
   teaching_style:'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
   category:['托福','雅思','商用英文','新聞英文'],
   courses:[
  {
  class_id:'5',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
      reserveDays: {
        Mon: false,
        Tue: false,
        Wed: true,
        Thu: false,
        Fri: true,
        Sat: true,
        Sun: false,
      },
},
]
},
  {
  teacher_id:'6',
	name: 'Grace',
  email: 'user6@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar:TeacherImg6,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
   teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
   category:['雅思','日常會話','旅遊英文'],
   courses:[
  {
  class_id:'6',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
      reserveDays: {
        Mon: false,
        Tue: false,
        Wed: true,
        Thu: false,
        Fri: true,
        Sat: false,
        Sun: false,
      },
},
],
},

 {
  teacher_id:'7',
	name: 'Tommy',
  email: 'user7@example.com',
  password:'a1234567890',
  nation:'taiwan',
  is_teacher: true,
  avatar: TeacherImg1,
  info: '我是一位有經驗的加拿大英語家教，熱愛教學，樂於幫助學生提升英語能力。',
  total_lesson_time: totalTime,
  week_lesson_time: weekTime,
  created_at: new Date(),
  updated_at: new Date(),
  rating:Math.floor(Math.random(56) * 10 + 1) * 0.5,
   teaching_style: 'Office ipsum you must be muted. Going spaces caught usabiltiy backwards. Info shower know rehydrate synergy indicators calculator cadence hit market. The backwards kimono managing beef close. Done panel join me look cc competitors comms scope container. Awareness catching nor ditching elephant helicopter chime read. Group community deck parking shark shoot plan right synergy couldSay crack air fastworks recap switch. Skulls request angel eager too 30,000ft. Run we key idea principles decisions innovation charts waste. Expectations into turn teeth illustration rundown first-order hit sorry loss. Support sorry world rundown then protocol globalize. Scope submit your driving sorry boy. Heads-up production value-added innovation low lot overflow catching strategies. Explore.',
   category:['托福','雅思','旅遊英文','日常會話','新聞英文'],
   courses:[
  {
  class_id:'7',
	name: 'Math',
  info: '可怕的數學',
  style:'困難的',
  link:'https://youtube.com',
  time:'30',
  avatar:'https://png.pngtree.com/png-vector/20221222/ourmid/pngtree-super-cute-cartoon-vector-bear-png-image_6504049.png',
  total_score: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  score_count: Math.floor(Math.random(56) * 10 + 1) * 0.5,
  created_at: new Date(),
  updated_at: new Date(),
        reserveDays: {
        Mon: true,
        Tue: true,
        Wed: true,
        Thu: false,
        Fri: false,
        Sat: true,
        Sun: false,
      },
},
]
}

];